---
groups:

- name: CAdvisor
  rules:

  - alert: ContainerKilled
    expr: time() - container_last_seen > 60
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container killed (instance {{ $labels.instance }})"
      description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: ContainerCpuUsage
    expr: (sum(rate(container_cpu_usage_seconds_total[3m])) BY (ip, name) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container CPU usage (instance {{ $labels.instance }})"
      description: "Container CPU usage is above 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: ContainerMemoryUsage
    expr: (sum(container_memory_usage_bytes) BY (ip) / sum(container_memory_max_usage_bytes) BY (ip) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container Memory usage (instance {{ $labels.instance }})"
      description: "Container Memory usage is above 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: ContainerVolumeUsage
    expr: (1 - (sum(container_fs_inodes_free) BY (ip) / sum(container_fs_inodes_total) BY (ip)) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container Volume usage (instance {{ $labels.instance }})"
      description: "Container Volume usage is above 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: ContainerVolumeIoUsage
    expr: (sum(container_fs_io_current) BY (ip, name) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container Volume IO usage (instance {{ $labels.instance }})"
      description: "Container Volume IO usage is above 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: SwitchIsDown
    expr: junos_up == 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Switch is down (instance {{ $labels.instance }})"
      description: "The switch appears to be down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HighBandwithUsage1gib
    expr: irate(junos_interface_transmit_bytes[1m]) * 8 > 1e+9 * 0.90
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "High Bandwith Usage 1GiB (instance {{ $labels.instance }})"
      description: "Interface is highly saturated for at least 1 min. (> 0.90GiB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HighBandwithUsage1gib
    expr: irate(junos_interface_transmit_bytes[1m]) * 8 > 1e+9 * 0.80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High Bandwith Usage 1GiB (instance {{ $labels.instance }})"
      description: "Interface is getting saturated for at least 1 min. (> 0.80GiB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: CorednsPanicCount
    expr: increase(coredns_panic_count_total[10m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "CoreDNS Panic Count (instance {{ $labels.instance }})"
      description: "Number of CoreDNS panics encountered\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


