---
groups:
- name: example
  rules:

  # Alert for any instance that is unreachable for >2 minutes.
  - alert: service_down
    expr: up == 0
    for: 1m
    labels:
      severity: critical
      environment: Production
      service: SERVICE_NAME
      customer: omniabo_noprod
      instance: '{{$labels.host}}'
    annotations:
      value: '{{$value}}'
      summary: "Instance {{ $labels.instance }} down"
      message: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."
      resource: '{{$labels.host}}'

  - alert: high_load
    expr: node_load1 > 0.5
    for: 1m
    labels:
      severity: warning
      customer: omniabo_noprod
      environment: Production
      instance: '{{$labels.host}}'
    annotations:
      value: '{{$value}}'
      summary: "Instance {{ $labels.instance }} under high load"
      description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."
